### ISSUE TITLE
Uncaught ReferenceError: require is not defined ...

### ISSUE THREAD

**Issue by hfuechter** [andig/fritzapi#1]
Hallo, ich hab das Script so eingebunden:

`<script>
var fritz = require('index.js');
 
fritz.getSessionID("username", "geheim").then(function(sid) {
    console.log("SID: " + sid);
});
</script>`

Das index.js liegt im gleichen Verzeichnis. 
Was mache ich falsch?

**Comment by andig** [comment]
Du verwendest kein Nodejs!

Viele Grüße,
Andreas

**Comment by hfuechter** [comment]
Stimmt, das ist bei mir offenbar nicht nutzbar. Schade.
