### ISSUE TITLE
unhandled rejection

### ISSUE THREAD

**Issue by impnguyen** [andig/fritzapi#11]
I tried to connect to Fritz with the object method. 

This error appears. (credentials are correct)
![image](https://user-images.githubusercontent.com/2463861/47968255-87d5f700-e067-11e8-91bb-420a2e01474a.png)

If I try the functional interface. I get this one: 
![image](https://user-images.githubusercontent.com/2463861/47968313-6f1a1100-e068-11e8-9f4f-d772b7cd0824.png)

Can somebody help me?

**Comment by andig** [comment]
Does not look like a valid url. Did you try `http://`? Does the `example.js` work for you?

**Comment by impnguyen** [comment]
I tried with http://192.168...... Same error. 

If I run example.js or index.js I get this error:
![image](https://user-images.githubusercontent.com/2463861/47969136-71ce3380-e073-11e8-8453-fab322d2c080.png)

**Comment by andig** [comment]
Yeah, thats obvious. Did you even install the dependencies?

**Comment by BolverBlitz** [comment]
pi@raspberrypi:~$ node example --username XXXX --password XXXX
{ error:
   { Error: getaddrinfo ENOTFOUND fritz.box fritz.box:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'fritz.box',
     host: 'fritz.box',
     port: 80 },
  response: undefined,
  options: { url: 'http://fritz.box/login_sid.lua' } }

And i get the same error when i try login with the Object-oriented interface.
Unhandled rejection

**Comment by BolverBlitz** [comment]
Had the same problem. In my Respberry where the wrong DNS Servers. IP wasn´t working.
After changing those it worked

**Comment by andig** [comment]
Closing due to missing feedback.
