### ISSUE TITLE
How can I log / persist data gathered from the Fritz devices?

### ISSUE THREAD

**Issue by qudarr** [andig/fritzapi#2]
Hi,

everything is working fine. I would like to log the temperature in order to understand which rooms are too cold / hot in the winter and how the temperature varies during the day.

How would be the best way to persist this data?

**Comment by andig** [comment]
You could check out http://volkszehler.org and log via HTTP POST or GET into a volszaehler installation.

**Comment by qudarr** [comment]
Hi Andig,
thanks for the quick response. I guess you meant http://volkszaehler.org ? (with AE)

Is there no way of getting the data out of homebridge directly?

**Comment by andig** [comment]
> Is there no way of getting the data out of homebridge directly?

None I'm aware of. You might ask in the homebridge forums.
