### ISSUE TITLE
Probleme mit Demo-Scripts

### ISSUE THREAD

**Issue by m24cl6000** [andig/fritzapi#20]
Hallo, hoffe ich mache das hier richtig, mein erstes Issue in Githuub ;-)

1) Wenn man sich nicht auf //Fritz.box als Standard Suchstring verlässt sondern eine eigene IP verwendet musste ich zwingend auch "http://" vor die IP, z.B. 192.168.178..1" setzen. Ansonsten bekomme ich 👍 Unhandled rejection (<{"error":{},"options":{"url":"192.168....>, no stack trace).

Also
var Fritz = require('fritzapi').Fritz;
var f = new Fritz("user", "password", "http://192.168.178.1");

2) getBasicDeviceStats braucht einen Parameter "ain".
Ich habe geändert 
    //new functions related to devices in version 7
    getBasicDeviceStats: function(ain) {
        return this.call(module.exports.getBasicDeviceStats, ain);

und es funktioniert. 

Habe ich etwas falsch verstanden oder sind das Fehler?

Gruß
Moritz

**Comment by andig** [comment]
Wenns funktioniert machst Du's richtig- bin jetzt nur nicht sicher was Du von mir brauchst? Wenn Du magst erstell gerne einen Pull Request mit den Änderungen.

Viele Grüße, Andreas

**Comment by andig** [comment]
Scheint sich erledigt zu haben ;)
