### ISSUE TITLE
ReferenceError: fritz is not defined

### ISSUE THREAD

**Issue by tklepzig** [andig/fritzapi#3]
Hi,

sometimes when using the fritzapi, I'm getting the error above. The cause is on line 65:

```
return fritz.getSessionID(...
```

I'm not quite sure, but I guess it has to be replaced with:

```
return module.exports.getSessionID(...
```

**Comment by andig** [comment]
"Sometimes" is very stange since the login is executed right at the start. How are you using/including/installing fritzApi?

**Comment by tklepzig** [comment]
It is not quite deterministic, it is when I use setSwitchOff/On. Sometimes the switch is turning off/on correctly, sometimes the first attempt fails with the exception above, the second one works.

I'm using it in a node.js server, locally hosted on a raspberry pi.

Besides that, when I open the file index.js in my node_modules, the mentioned line is marked red, because there is no variable `fritz` anywhere defined.

**Comment by andig** [comment]
So its your own code? Can you share it?

**Comment by tklepzig** [comment]
Here is a snippet from the call, nothing special:

```
const fritzApi = new Fritz("user", "password");

...

fritzApi.setSwitchOff("1234567890");

```

This code sometimes switch the device off, sometimes it runs into the mentioned exception.

**Comment by andig** [comment]
Ah, I see. Good catch! I have no idea why that ever works at all but apparently it does. With your suggested change it should work? I'll update the module asap.

**Comment by tklepzig** [comment]
Yeah, I changed the line and tested it the last two days, the error didn't occure anymore, so it should work.

**Comment by andig** [comment]
Closed via 74a3008396c96230610e671c787aa1dc9a4cf345

**Comment by tklepzig** [comment]
Thanks!

**Comment by andig** [comment]
Danke für die Analyse 👍🏻

Viele Grüße,
Andreas
