### ISSUE TITLE
getSID fails at first call

### ISSUE THREAD

**Issue by lavolp3** [andig/fritzapi#33]
```
    getSID: function() {
        return this.sid;
    },
```
This provides an empty SID if ```this.call()```has not been called by any of the other functions in the current session.
Any call via this.call fills ```this.sid``` with the current sid. Only after that, the getSID function is useful

**Comment by andig** [comment]
Why do you think that's a problem? With empty sid, api call will fail as expected.

**Comment by lavolp3** [comment]
I thought this was not intended but understand it is. Will close this.
