### ISSUE TITLE
Support for FRITZ DECT 440 and 550?

### ISSUE THREAD

**Issue by altso2222** [andig/fritzapi#50]
Is there any support planned for the FRITZ DECT 440 switch and the FRITZ DECT 500 light bulb? 

Inititial discussion: https://community.home-assistant.io/t/support-for-avm-fritz-dect-switch-440-and-light-bulb-500/224433/13

**Comment by vonglahn** [comment]
me too

**Comment by altso2222** [comment]
To allow the support for the FRITZ DECT 440 switch and the FRITZ DECT 500 light bulb, the HA dependency to python-fritzhome has to be bumped to version 0.6.0.

Link to current version of python-fritzhome: https://github.com/hthiery/python-fritzhome/tree/0.6.0

**Comment by HubertusH** [comment]
So i see version 0.6.0 is ready to support Fritz Dect 440 - we wait for implementing in fritzapi. i need this forward for node-red-contrib-fritzapi to use this in node-red. Thank you

**Comment by andig** [comment]
Happy to take a PR for what you're missing
