### ISSUE TITLE
Possible to add API for temperature sensor adjustment value?

### ISSUE THREAD

**Issue by miz-online** [andig/fritzapi#60]
Hi, I plan to control my heater thermostats through node-red. 
My issue is that depending on outside temperature I need to set the deviation on the sensors to compensate that rooms are cooling off faster, heaters are warmer and thus the temperature measurement on the heaters does not match with room temperature.
As said, this is dependent on outside temperature, so I created a node-red script that uses the current temperature together with the 3h weather forecast to set a deviation factor. Unfortunately, the node-red fritzapi module does not support setting the deviation, as it is just a wrapper around this API.
Is there any chance to add this feature?

thanks
Michael

**Comment by andig** [comment]
I don‘t think thats in the scope of this library. Seems you‘re already successfully implementing it outside of fritzapi.

**Comment by miz-online** [comment]
Hi, too bad, This was the last bit that was missing - really setting the value. But in the meantime I had a look at the fritz docs and it seems there is no such API - one needs to use a web Url to set it obviously :-(
Thanks anyway..

**Comment by andig** [comment]
You can just set the higher value you need
